name: Android APK Build

on:
  push:
    branches:
      - main   
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Set up keystore.properties
      run: |
        echo "storeFile=$HOME/keystore.jks" > $HOME/keystore.properties
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> $HOME/keystore.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> $HOME/keystore.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> $HOME/keystore.properties

    - name: Copy keystore file
      run: |
        mkdir -p $HOME/keystore
        echo "${{ secrets.KEYSTORE_FILE_PATH }}" > $HOME/keystore/keystore.jks
        ls -la $HOME/keystore
        ls -la $HOME
        pwd

    - name: Set up Android SDK
      run: |
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
        unzip commandlinetools-linux-6858069_latest.zip -d android-sdk
        mkdir -p $HOME/Android/Sdk/cmdline-tools
        mv android-sdk/cmdline-tools $HOME/Android/Sdk/cmdline-tools/latest
          
        echo "y" | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --update
        $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

    - name: Build APK
      run: ./gradlew assembleRelease  
